[phases.setup]
nixPkgs = ["nodejs_18", "nodePackages.npm"]

[phases.install]
cmds = ["npm install", "cd server && npm install"]

[phases.build]
cmds = ["echo 'Server build complete'"]

[start]
cmd = "node server/index.js"
